### PR TITLE
Final changes of the day...

### PR DESCRIPTION
**Pull request by loganpmahan**
Final changes for the day. Pretty much finished up the UI layout after restarting in C#. Unfortunately was unable to link actions to clicking buttons because I didn't have the code (can get right on this as soon as
Farshad gives sample code to copy). Also, add/edit pages need to be merged and added.

### CODE REVIEW

**Comment by aaronescott** [comment]
The code can be found on the mainpage in the login button. Just change the pages to what you where you want it to go. 

I'm not sure which way we want to go with the add/edit pages, but I have two of the separate add/edit pages done so far.

**Comment by aaronescott** [comment]
@loganpmahan @fdmomtaz The code looks good. I noticed you changed the position of the page title and it looks good. Some of the buttons did become unaligned, however. Originally, the code didn't run, so I did change that. One of the buttons wasn't working I guess.

**Comment by loganpmahan** [comment]
That's strange they're coming unaligned because I placed them within a
grid. I'll take a look at that.

**Comment by aaronescott** [comment]
@loganpmahan It seems like a lot of the page elements have come off the grid. It is fine in VS, but when I run the program, some buttons won't show up.

**Comment by loganpmahan** [comment]
I'll take a look at it.

**Pull request merged**
