### PR TITLE
update

### PR DESCRIPTION
**Pull request by loganpmahan**
Added a home page, inventory page, vendor information page, and a vendor list page. Added a home button to the other pages. I still think there's room for improvement but we're off to a good start.

### CODE REVIEW

**Comment by loganpmahan** [comment]
I can see the .xaml files that I made and uploaded... but they won't load on the project itself. I'm not sure what I did wrong here. For some reason they're different than the other pages. They don't have a .cpp or .h file.

**Comment by fdmomtaz** [comment]
@loganpmahan you should add pages by taking the following steps:
1. right click on the project
2. click on add
3. click on new item
4. on the left click on xaml
5. click on blank page
6. type the name of the page in the box in the bottom
7. click on add

**Comment by loganpmahan** [comment]
Ah, thank you. I'll just have to start over on those pages then lol.

**Comment by fdmomtaz** [comment]
@loganpmahan not at all, just copy and paste your code for the xaml pages into a file. create a new branch. create pages with new method and copy and paste the xaml pages into the new pages

**Pull request closed without merging**
