### PR TITLE
Event details page

### PR DESCRIPTION
**Pull request by aaronescott**
Not sure if done correctly. I could not use XAML because the updated XAML version would not load. Not sure if I did something wrong when opening that version.

### CODE REVIEW

**Comment by aaronescott** [comment]
Not exactly sure what the conflicting files are either. I will do the add/edit page by Sunday night as well.

**Comment by fdmomtaz** [comment]
So everything we had until Wednesday was removed and recreated, so the UI you created from the last time it's not there anymore. The problem is that you didn't do a pull from the master before doing your changes

**Comment by aaronescott** [comment]
@fdmomtaz Got it. I did a pull but nothing loaded. Visual studio told me I had to update so I will try that.

**Comment by aaronescott** [comment]
@fdmomtaz I may be missing something, but when I open Visual Studio now, it says that the project "inventory system" is unavailable. There are no files as before.

**Comment by fdmomtaz** [comment]
@aaronescott the easiest way to fix this situation is that you do a new clone in a new directory.

**Comment by aaronescott** [comment]
@fdmomtaz I actually did this. What I am having trouble with is what to do after opening inventory system.sln. When i get into visual studio it says there are 0 projects. I tried to create a new project but this doesn't seem to work. Sorry for the trouble.

**Comment by fdmomtaz** [comment]
try these steps:
1. create new directoy
2. git clone https://github.com/fdmomtaz/inventory-system.git
3. open "Inventory System.sln"
4. change to "x64" from "ARM" on top
5. click on "Local Machine" on top

let me know if theses steps work.

**Comment by fdmomtaz** [comment]
@loganpmahan do you have same problem with cloning and getting the solution to work?

**Comment by loganpmahan** [comment]
I haven't tried anything yet. I'm not home

**Comment by aaronescott** [comment]
@fdmomtaz I did what you said and it had me reinstall visual studio. That took a while last night but it is working now. I should have it done by tonight. Thanks for the help.

**Pull request closed without merging**
