### PR TITLE
Events add edit

### PR DESCRIPTION
**Pull request by aaronescott**
I added an add/edit page for events. I am not sure if I have used the correct tools for each part of the page, ie using textboxes/textblocks when they should be used. Hopefully everything is used correctly. I added in a TempEvents button on the homepage to get to events. From there click on Add New Event to get to the Add/Edit page. I was also thinking about having the information on top (Event Name, Event ID) in a different background color like Wards but could not find a way to change the font in a text box.

I wanted to see if this was a good enough design before creating the other pages.

Also, I can't request a review from Logan.

And merging doesn't appear to be locked if you want to lock that again.

### CODE REVIEW

**Comment by fdmomtaz** [comment]
Not bad but checkout my pull request and let me know what you think. I combined the details and add/edit page so they are both done on one page.

**Comment by aaronescott** [comment]
@fdmomtaz I checked it out. So it would be the events and items in the two tabs and when you click on an item the information appears in the top boxes and this information can be edited by the user?

**Comment by fdmomtaz** [comment]
@aaronescott yes that's the approach i had in mind but we can ask our users which one is better

**Comment by fdmomtaz** [comment]
@aaronescott make sure you do a pull before any changes because you have conflicts with the master code. i'll fix the conflicts

**Comment by loganpmahan** [comment]
When I get back from brunch I'll update the code with button functionality.

**Comment by aaronescott** [comment]
@fdmomtaz Are we planning on merging this or going with another route. If we don't want to merge it you don't really have to fix the conflicts.

**Comment by fdmomtaz** [comment]
@aaronescott Since you also would like to go with the other route, ill just close this pull request and if we change our minds at a later point we'll get back to this one

**Pull request closed without merging**
