### PR TITLE
Home page, Vendor Info, Vendor List, etc..

### PR DESCRIPTION
**Pull request by loganpmahan**
Here we go, should be good to go!

### CODE REVIEW

**Comment by aaronescott** [comment]
@loganpmahan I can't actually see any changes on the new branch.

**Comment by loganpmahan** [comment]
I'm looking at the changes on git and it says 200+ new changes with a Home
Page, Vendor List, Vendor Info.. weird

**Comment by fdmomtaz** [comment]
@aaronescott click on "Files Changed" on top to see the changes

**Comment by fdmomtaz** [comment]
@loganpmahan 200+ refers to number of lines

**Comment by aaronescott** [comment]
@fdmomtaz I was trying to see them on VS. Is that possible?

**Pull request merged**
